## library() calls go here
library(conflicted)
library(dotenv)
library(drake)
library(data.table)
library(tidyverse)
library(googlesheets4)
library(janitor)
library(scales)
library(mgcv)
library(EpiNow2) # remotes::install_github("epiforecasts/EpiNow2")
library(frs)     # remotes::install_github("ellisp/frs-r-package/pkg")
library(patchwork)
library(glue)
library(RColorBrewer)
library(polite)
library(rvest)
conflicted::conflict_prefer("pluck", "purrr")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("gather", "tidyr")
library(rmarkdown)
